---
title: "Deep Work Supervisor"
author: "Will Bidstrup"
date: "2019-01-12"
output: html_document
---

Using R Markdown for interactive exploration.  

```{r}
# TODO - create time of day variable 
```


```{r}
library(here)
library(tidyverse)
library(padr)
```

```{r}
d <- read_csv(here("/data_raw/BeFocused.csv"))
```

```{r}
str(d)
```

# Clean  

First remove the first row.  

```{r}
d <- d[-1, ]
```

Also remove the 'Other' category as it holds no insight.  

```{r}
d <- d %>%
  filter(`Assigned task` != "Other")
```

Then get the date column into shape. By default it looks like this;  

```{r}
head(d$`Start date`)
```

I change it into a date format.  

```{r}
d$date_full <- d$`Start date`

d <- d %>%
  separate(date_full, into = c('Date', 'Time'), sep = 11)

d$Date <- as.Date(d$Date, format = "%d %b %Y")

```

```{r}
d$Duration <- 30 # Assume 30mins spent including relax/reflect time
d$hours <- d$Duration / 60
```


```{r}
# Gather tasks into categories

unique(d$`Assigned task`)
d$category <- ifelse(d$`Assigned task` %in% c("YABP", "Experiment In Art", "Summoner Of Games", "Data Science Explorer", "YABP", "RPG Prep", "Correspondance"), "Craft", 
                     ifelse(d$`Assigned task` == "P.S Work High Value", "Work",
                            ifelse(d$`Assigned task` == "Wealth", "Wealth",
                                   ifelse(d$`Assigned task` == "Study", "Study", "Other"))))
```


# Export

```{r}
write_csv(d, "data_transformed/curated_BeFocused.csv")
```


```{r}
# What is a normal day like?
daily_all <- d %>%
    pad %>%
  group_by(Date) %>%
  summarise(hours_in_day = sum(hours, na.rm = T))

daily_all$avail_time <- 8
daily_all$focused_prop <- round((daily_all$hours_in_day / daily_all$avail_time), digits = 2)

daily <-d %>%
  group_by(Date, category) %>%
  summarise(hours_in_day = sum(hours, na.rm = T))


write_csv(daily_all, "data_transformed/daily_all.csv")
write_csv(daily_all, "data_transformed/daily.csv")

```



```{r}
# What is weekly like?
library(lubridate)

weekly <- daily

# Assign week number
weekly <- weekly %>%
  mutate(week = week(Date))

# Assign year as int
weekly$year <- ifelse(weekly$Date >= "2019-01-01", 2019, 2018)

# Collapse into weekly data

weekly <- weekly %>%
  group_by(week, category, year) %>%
summarise(hours_in_week = sum(hours_in_day))

# Export 

write_csv(weekly, "data_transformed/weekly.csv")
```


```{r}
# Trend of time spent
trend_type <- d %>%
  group_by(Date, category) %>%
  summarise(time_spent = sum(hours, na.rm = T))

write_csv(trend_type, "data_transformed/trend_type.csv")
```


```{r}
overall_deep_work_score <- daily_all %>%
  summarise(total_avail = sum(avail_time, na.rm = T),
            total_focus = sum(hours_in_day, na.rm = T),
            focus_score = total_focus / total_avail) 

write_csv(overall_deep_work_score, "data_transformed/deep_work_score.csv")
```


# Visuals


```{r}
# Deep Work quantity by day
ggplot(data = trend_type %>%
         select(Date, time_spent) %>%
         group_by(Date) %>%
         summarise(total_per_day = sum(time_spent)), aes(x = Date, y = total_per_day)) +
  geom_point() +
  geom_smooth()

```




```{r}
ggplot(data = daily, aes(x = category, y = hours_in_day, col = category)) +
  geom_boxplot(alpha = 0.5) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
  coord_flip()
```

```{r}
ggplot(data = daily_all, aes(x = hours_in_day)) +
  geom_histogram() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) 
```

```{r}
# Look at effective use of time
ggplot(data = daily_all, aes(x = focused_prop)) +
  geom_histogram() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) 

```

```{r}
# Trend of focus % over time - am I getting better or worse??
ggplot(data = daily_all, aes(x = Date, y = focused_prop)) +
  geom_point() +
  geom_smooth() +
  theme_minimal()

```

```{r}
ggplot(data = trend_type, aes(x = time_spent, fill = category)) +
  geom_density(alpha = 0.5) +
  theme_minimal()

```




```{r}
ggplot(data = weekly, aes(x = hours_in_week, fill = category)) +
  geom_density(alpha = 0.5) +
  theme_minimal()

```


```{r}
ggplot(data = trend_type, aes(x = time_spent, fill = category)) +
  geom_density(alpha = 0.5) +
  theme_minimal() +
  facet_wrap(~ category, nrow = 3)

```


## Simple shiny prototype

How much deep work of a particular type have I been doing?

```{r}
# Create data which is daily info of number of hours by category
cat_names <- unique(daily$`Assigned task`)

```


```{r}
ggplot(data = daily, aes(x = Date, y = hours_in_day, col = category)) +
  geom_line() +
  theme_minimal()
```


```{r}
ggplot(data = weekly, aes(x = week, y = hours_in_week)) +
  geom_line() +
  theme_minimal() +
  facet_grid(. ~ year)
```

```{r}
ggplot(data = daily, aes(x = hours_in_day)) +
  geom_histogram() +
  theme_minimal()
```

